class AutoCompleteDict(dict):
    def __getattr__(self, name):
        if name in self:
            return self[name]
        raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")

    def __setattr__(self, name, value):
        self[name] = value


def search_query_template(token, state_id, district_id, current_page=0):
    data = {
        '__RequestVerificationToken': token,
        'Type': 'Promoter',
        'ID': '0',
        'pageTraverse': '1',
        'Project': '',
        'hdnProject': '',
        'Promoter': '',
        'hdnPromoter': '',
        'AgentName': '',
        'hdnAgent': '',
        'CertiNo': '',
        'hdnCertiNo': '',
        'State': '27',
        'hdnDivision': '',
        'hdnDistrict': district_id,
        'hdnDTaluka': '',
        'hdnVillage': '',
        'hdnState': state_id,
        'District': district_id,
        'hdnPincode': '',
        'PinCode': '',
        'CompletionDate_From': '',
        'hdnfromdate': '',
        'CompletionDate_To': '',
        'hdntodate': '',
        'PType': '',
        'hdnPType': '',
        'CurrentPage': str(current_page),
        'Command': 'Next'
    }

    return data


def projects_data_template():
    data = {
        "Project Name": "",
        "Promoter Name": "",
        "Last Modified Date": "",
        "View Certificate": "",
        "Certificate Date": "",
        "Do you have any Past Experience ?": "",
        "Pin Code": "",
        "Office Number": "",
        "Website URL": "",
        "Project Status": "",
        "Proposed Date of Completion": "",
        "Revised Proposed Date of Completion": "",
        "Litigations related to the project ?": "",
        "Project Type": "",
        "Are there any Promoter(Land Owner/ Investor)": "",
        "Division": "",
        "District": "",
        "Taluka": "",
        "Village": "",
        "Street Pin Code": "",
        "Total Plot/Project area (sqmts)": "",
        "Total Number of Proposed Building/Wings (In the Layout/Plot)": "",
        "Total Recreational Open Space as Per Sanctioned Plan": "",
        "Sanctioned FSI of the project applied for registration (Sanctioned Built-up Area)": "",
        "Built-up-Area as per Proposed FSI (In sqmts) ( Proposed but not sanctioned) (As soon as approved, should be immediately updated in Approved FSI)": "",
        "Permissible Total FSI of Plot (Permissible Built-up Area)": "",
        "Bank Name": "",
        "IFSC Code": "",
        "Community Buildings Available": "",
        "Community Buildings Percent": "",
        "Number of Sanctioned Floors": "",
        "Total no. of open Parking as per Sanctioned Plan (4-wheeler+2-Wheeler)": "",
        "Number of Closed Parking": "",
        "Carpet Area (in Sqmts)": "",
        "Excavation": "",
        "X number of Slabs of Super Structure": "",
        "Installation of lifts, water pumps, Fire Fighting Fittings and Equipment": "",
        "Number of Apartment": "",
        "Number of Booked Apartment": "",
        "carpet_area_apartments_0_30": "",
        "carpet_area_booked_apartments_0_30": "",
        "carpet_area_apartments_30_45": "",
        "carpet_area_booked_apartments_30_45": "",
        "carpet_area_apartments_45_60": "",
        "carpet_area_booked_apartments_45_60": "",
        "carpet_area_apartments_60_90": "",
        "carpet_area_booked_apartments_60_90": "",
        "carpet_area_apartments_90_120": "",
        "carpet_area_booked_apartments_90_120": "",
        "carpet_area_apartments_120_150": "",
        "carpet_area_booked_apartments_120_150": "",
        "carpet_area_apartments_150_200": "",
        "carpet_area_booked_apartments_150_200": "",
        "carpet_area_apartments_more_than_200": "",
        "carpet_area_booked_apartments_more_than_200": "",
        "apartments_1rk": "",
        "booked_apartments_1rk": "",
        "apartments_1bhk": "",
        "booked_apartments_1bhk": "",
        "apartments_2bhk": "",
        "booked_apartments_2bhk": "",
        "apartments_3bhk": "",
        "booked_apartments_3bhk": "",
        "apartments_4bhk": "",
        "booked_apartments_4bhk": "",
        "apartments_5bhk": "",
        "booked_apartments_5bhk": "",
        "apartments_shops": "",
        "booked_apartments_shops": "",
        "apartments_bungalow": "",
        "booked_apartments_bungalow": "",
        "apartments_office_space": "",
        "booked_apartments_office_space": "",
        "apartments_others": "",
        "booked_apartments_others": "",
        "form_4": "",
        "conveyance": "",
        "complaint_details":"",
        "litigation_details":""
    }

    return data
